DROP TABLE IF EXISTS organization;

CREATE TABLE organization (
	ID		BIGINT			PRIMARY KEY AUTO_INCREMENT,
	HQ_CD	VARCHAR(200),
	HQ_NM	VARCHAR(200),
	AGNC_CD	VARCHAR(200),
	AGNC_NM	VARCHAR(200),
	GA_CD	VARCHAR(200),
	GA_NM	VARCHAR(200),
	BRN_CD	VARCHAR(200),
	BRN_NM	VARCHAR(200)
);